name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - matplotlib
  - pandas
  - pip
  - pyarrow
  - pip:
      - wandb==0.13.9
      - mlflow==2.2.2
      - sktime==0.15.1
      - seaborn
      - xgboost
      - shap