name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=20.3.3
  - pandas=1.2.4
  - pip:
      - wandb==0.13.9
      - mlflow==2.2.2