main:
  # Set this to null if you are running in prod
  project_name: ihm
  experiment_name: development
  steps: all
  models: random_forest
etl:
  sample: "MiningProcess_Flotation_Plant_Database.csv"
data_check:
  kl_threshold: 0.2
deploy:
  module: "sklearn.ensemble"
  estimator: "RandomForestRegressor"
  model_name: "random_forest"
  tag: "prod"
modeling:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
  val_size: 0.2
  # Fix this for reproducibility, change to have new splits
  random_seed: 42
  # Get Time Series and Tabular Data
  ts: 1
  tx: 1
  # For the Time Series Data, from which date should we keet for testing
  ts_test_size: "2017-08"
  kfolds: 5
  random_forest:
    module: "sklearn.ensemble"
    estimator: "RandomForestRegressor"
    n_estimators: 50
    max_depth: 5
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    criterion: absolute_error
  xgboost:
    module: "xgboost"
    estimator: "XGBRegressor"
    n_estimators: 200
    max_depth: 10
    learning_rate: 0.001
    random_state: 42
  lasso:
    module: "sklearn.linear_model"
    estimator: "Lasso"
    alpha: 0.1