name: ihm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - hydra-core=1.3.1
  - matplotlib
  - pandas
  - git
  - pip
  - pip:
      - mlflow==2.1.1
      - wandb==0.13.9
      - protobuf