name: data_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - requests=2.24.0
  - pandas=1.2.4
  - pip:
      - wandb==0.13.9
      - mlflow==2.2.2
      - sktime==0.15.1