name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=1.2.2
  - pillow=8.1.2
  - pip:
      - wandb==0.13.9
      - omegaconf==2.0.6
