name: tx_pepiline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - pillow=8.1.2
  - pip:
      - wandb==0.13.9
      - mlflow==2.2.2
      - scikit-learn==1.0.2
      - omegaconf==2.0.6
      - xgboost
      - matplotlib
